name: "platform-prd"
description: "平台运营域PRD编写流程"
author: "Clara"

config_source: "{project-root}/chongqing-product-design/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated

installed_path: "{project-root}/chongqing-product-design/workflows/platform-prd"
template: "{installed_path}/template.md"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

default_output_file: "{output_folder}/【Clara生成PRD】平台运营端_{{workflow_name}}_PRD_V1.0.md"

standalone: true
