name: "merchant-prd"
description: "商家域PRD编写流程"
author: "Clara"

config_source: "{project-root}/chongqing-product-design/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated

installed_path: "{project-root}/chongqing-product-design/workflows/merchant-prd"
template: "{installed_path}/template.md"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

default_output_file: "{output_folder}/商家域PRD-{{workflow_name}}-{{date}}.md"

standalone: true
